name: End-to-ednd Cypress Tests

on:
    pull_requests:
    branches: ["main"]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress.io
              uses: cypress-io/github-action@v5.0.0
